name: "Scheduled tests"

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 2 * * 1-5' # 00:00 every monday

jobs:
  schedule-coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install node modules
      run: yarn install --frozen-lockfile

    - name: Compile contracts
      run: yarn run compile

    - name: Run the test
      run: yarn run cov

    - name: Upload coverage artifact
      uses: actions/upload-artifact@v4
      with:
        name: coverage-report
        path: path/to/coverage/report/ # Ajusta esta ruta a la salida de tus tests

  schedule-fuzzer:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    env:
      NODE_OPTIONS: "--max_old_space_size=6144"
      LOOPS: 5000
      CHANGE_PRICE_AT: '300,600,...'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js 18
      uses: actions/setup-node@v4
      with:
        node-version: 18

    - name: Install node modules
      run: yarn install --frozen-lockfile

    - name: Compile contracts
      run: yarn run compile

    - name: Run the test
      run: yarn run fuzzing_fasset

    - name: Archive fuzzer log
      uses: actions/upload-artifact@v4
      with:
        name: fuzzer-log
        path: test_logs/fasset-fuzzing.log # Ajusta la ruta si cambia
